import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Academy ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // specifying that only React Element/Node comes , nothing else
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="">
          <Navbar/>
        </div>
        {children}</body>
    </html>
  );
}
